apiVersion: v1
kind: Pod
metadata:
  name: annotationpod
  annotations:
    owner: "Mimar ASLAN"
    notification-email: "mimaraslan@gmail.com"
    releasedate: "01.01.2021"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  containers:
  - name: annotationcontainer
    image: nginx
    ports:
    - containerPort: 80