apiVersion: v1
kind: Pod
metadata:
  name: crashloopbackpod
spec:
  restartPolicy: Always
  containers:
  - name: crashloopbackcontainer
    image: ubuntu:latest
    command: ['sh', '-c', 'echo "Hello, Kubernetes!" && sleep 20']